AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Microservicios para realizar el scrapping del sitio web comprasmx




Mappings:
  Parametros:
    dev:
      STAGE: dev
      NameAPI: DEV-API
      RoleName: DevComprobarContratosRole 
      #PolicyName: dev-GrabacionesS3Policys
      NameBucket: archivos-eventos
      CarpetaEvento: dev-compramex
      CarpetaGuardar: dev-compramex-clasificados
      CarpetaParcial: dev-compramex-parcial
      HOST: "{{resolve:ssm:/dev/mariadb/host}}"
      USER: "{{resolve:ssm:/mariadb/user/licitaciones}}"
      PASSWORD: "{{resolve:ssm:/mariadb/password/licitaciones}}"
      DBNAME: "{{resolve:ssm:/mariadb/db-name}}"
      PORT: "{{resolve:ssm:/mariadb/port}}"
      DIALECT: "{{resolve:ssm:/mariadb/dialect}}"
      STACK: dev-compras-mx
    prod:
      STAGE: v1
      NameAPI: API
      #LayerCuestionario: CuestionarioLayer
      #NameBucket: grabaciones-encuestas
      #BucketSid: PermitirAccesoDominiosCORS
      RoleName: ComprobarContratosRole 
      #PolicyName: GrabacionesS3Policys
      NameBucket: archivos-eventos
      CarpetaEvento: compramex
      CarpetaGuardar: compramex-clasificados
      CarpetaParcial: compramex-parcial
      HOST: "{{resolve:ssm:/prod/mariadb/host}}"
      USER: "{{resolve:ssm:/mariadb/user/licitaciones}}"
      PASSWORD: "{{resolve:ssm:/mariadb/password/licitaciones}}"
      DBNAME: "{{resolve:ssm:/mariadb/db-name}}"
      PORT: "{{resolve:ssm:/mariadb/port}}"
      DIALECT: "{{resolve:ssm:/mariadb/dialect}}"
      STACK: compras-mx
    layers:
      PuppeterLayer: arn:aws:lambda:us-east-1:701120439971:layer:PuppeteerLayer:19


Parameters:
  Entorno:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Variables de entorno
    
  ModelLayerParameterArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /prod/directorio/layers/models
  
  SequelizeLayerParameterArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /prod/directorio/layers/sequelize  

Resources:
  ApiComprasMx:
    Type: AWS::Serverless::Application
    Properties:
      Location: api/api.yaml
      Parameters:
      #Escenario
        STAGE: !FindInMap [Parametros, !Ref Entorno, STAGE]
        NameAPI: !FindInMap [Parametros, !Ref Entorno, NameAPI]
      #Contratos
        ObtenerContratosFunctionArn: !GetAtt LambdasContratos.Outputs.ObtenerContratosFunctionArn
        
      #Autorizar S3
        #OtorgarPermisosS3Arn: !GetAtt LambdasPermisosS3.Outputs.OtorgarPermisosS3Arn
      

  LambdasContratos:
    Type: AWS::Serverless::Application
    Properties:
      Location: lambdas/contratos.yaml
      Parameters:
        RoleName: !FindInMap [Parametros, !Ref Entorno, RoleName]
        NameBucket: !FindInMap [Parametros, !Ref Entorno, NameBucket]
        CarpetaEvento: !FindInMap [Parametros, !Ref Entorno, CarpetaEvento]
        CarpetaGuardar: !FindInMap [Parametros, !Ref Entorno, CarpetaGuardar]
        CarpetaParcial: !FindInMap [Parametros, !Ref Entorno, CarpetaParcial]
        HOST: !FindInMap [Parametros, !Ref Entorno, HOST]
        USER: !FindInMap [Parametros, !Ref Entorno, USER]
        PASSWORD: !FindInMap [Parametros, !Ref Entorno, PASSWORD]
        DBNAME: !FindInMap [Parametros, !Ref Entorno, DBNAME]
        PORT: !FindInMap [Parametros, !Ref Entorno, PORT]
        DIALECT: !FindInMap [Parametros, !Ref Entorno, DIALECT]
        STACK: !FindInMap [Parametros, !Ref Entorno, STACK]
        ModelsLayers: !Ref ModelLayerParameterArn
        SequelizeLayer: !Ref SequelizeLayerParameterArn
        PuppeterLayer: !FindInMap [Parametros, layers, PuppeterLayer]

        

