AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  api

Parameters:
  ObtenerContratosFunctionArn:
    Type: String
  STAGE:
    Type: String
  NameAPI:
    Type: String

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref STAGE
      Name: !Sub ${NameAPI}-ComprasMX
      Variables:
        NameAPI: !Ref NameAPI
      OpenApiVersion: 3.0.1
      DefinitionBody:
        "Fn::Transform":
          Name: "AWS::Include"
          Parameters:
            Location: openapi.yaml
      TracingEnabled: true
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  ApiGatewayExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: ApiGatewayExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action: lambda:*
                Effect: Allow
                Resource:
                  - Ref: ObtenerContratosFunctionArn

